### ISSUE TITLE
Saving not working

### ISSUE THREAD

**Issue by grimpunch** [Northfear/homm3hd-vita#1]
Not sure if it's a quirk of my installation, but so far every autosave fails with an in game error message and so do manual saves

**Comment by Northfear** [comment]
Haven't seen this one before. Is it working after restarting the game?

**Comment by grimpunch** [comment]
I've given it another test after restarting, same result
![16651823002181478268736549323909](https://user-images.githubusercontent.com/1707054/194671860-72e0eb7f-22f6-46dc-b47f-63408577cf53.jpg)

**Comment by Northfear** [comment]
What map are you playing on? Or is it reproducible on all of the maps + campaign?

**Comment by grimpunch** [comment]
I tried it on one of the first "Single Scenario" maps

**Comment by Northfear** [comment]
Or, I'm really confused by this, since I can't reproduce it no matter what.
So either something is wrong with install or maybe some plugin is causing it.
Could you drop a list of installed plugins? Because I'm running low on ideas. 

Edit: Ok, I was able to reproduce the bug. Looking into it

**Comment by Northfear** [comment]
Ok, so basically you have to create an empty "pref" folder inside `ux0:data/homm3hd/`. It was empty inside the obb, so you've probably just skipped it. I should probably check if it's there during the start of the game and create it if needed.

**Comment by grimpunch** [comment]
Thanks, that makes sense, and is probably the solution.
I'll report back later on when i have some time to check!

**Comment by Northfear** [comment]
Fixed in v1.0.2
https://github.com/Northfear/homm3hd-vita/releases/tag/v1.0.2

**Comment by grimpunch** [comment]
Confirmed your fix
