### ISSUE TITLE
Nintendo Switch Port

### ISSUE THREAD

**Issue by jonasmare** [Northfear/homm3hd-vita#2]
Possible to have this ported to the Switch too?
I know that HOMM2 can be played on the Switch but I don't think HOMM3 was ever ported and the Switch is also based on ARM !

**Comment by Northfear** [comment]
Short answer: no
Long answer: It's not the kind of port like fheroes2 is. This is a "wrapper" of Android version of HoMM3. In theory those kind of ports are possible on Switch too (Max Payne), but this requires aarch64 binary (64-bit ARM). And no such version of HoMM3 HD was ever released.
Android dual boot is probably the easiest way of playing HoMM3 on switch right now.

**Comment by jonasmare** [comment]
humm there's this https://github.com/vcmi/vcmi
Dunno if it would help, they have android but not Switch :(

**Comment by Northfear** [comment]
VCMI could be ported in theory, yes. But that's not an easy task and would require someone with a lot of Switch experience (and time)
