### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by akopotilov** [Northfear/homm3hd-vita#3]
Hi! I have followed the installation guide, using kubridge and rePatch plugins, but my game crashes on startup without loading anything.
It does look like I did something wrong with the installation, but I double checked everything twice. The only thing that I have only version 1.1.5 of the original HOMM3 Android vpk and files. Could that be the issue? Could you please help me trace the problem?

Attached my crash dump. [psp2core-1703023367-0x00000b2657-eboot.bin.zip](https://github.com/Northfear/homm3hd-vita/files/13720968/psp2core-1703023367-0x00000b2657-eboot.bin.zip)

**Comment by Northfear** [comment]
Yeah, 1.1.5 is definitely a problem. The wrapper was made with 1.1.6 is mind, so any other version is unsupported.
