### ISSUE TITLE
Crash on start (apk version 1.1.6)

### ISSUE THREAD

**Issue by akopotilov** [Northfear/homm3hd-vita#4]
Hi! I've redone all steps from the installation guide using original game v1.1.6 (deleted old homm3hd/data, extracted new .obb files and libhomm3.so file from apk), and the issue is still the same as in my [previous report](https://github.com/Northfear/homm3hd-vita/issues/3). The problem is still the same, game crashes on startup. Could you please help?

Crash dump is here: [psp2core-1703097130-0x00002c38ab-eboot.bin.zip](https://github.com/Northfear/homm3hd-vita/files/13731041/psp2core-1703097130-0x00002c38ab-eboot.bin.zip)

**Comment by Northfear** [comment]
Looks like it's crashing on image load. Something went wrong with data install most likely.
Delete everything, make sure that you're using 1.1.6 game APK and proper obb files (`main.1113.com.ubisoft.mightandmagic.heroesiii.obb` and `patch.1110.com.ubisoft.mightandmagic.heroesiii.obb`)
Show me the content for ux0:data/homm3hd/ if it still fails.

**Comment by akopotilov** [comment]
Sadly, redoing everything from scratch didn't help.
This is the latest crash dump: [psp2core-1703107872-0x0000a02ded-eboot.bin.zip](https://github.com/Northfear/homm3hd-vita/files/13732928/psp2core-1703107872-0x0000a02ded-eboot.bin.zip)
This is homm3d folder contents and folder info. Please let me know what more I can do to help you identify the cause.
![image](https://github.com/Northfear/homm3hd-vita/assets/2396354/ab5069f8-a2c0-4894-bd2e-24b66f68d6ae)
![image](https://github.com/Northfear/homm3hd-vita/assets/2396354/110de590-af6c-4460-8c74-399f3d2985e0)

**Comment by Northfear** [comment]
Honestly github issues is not a right place for troubleshooting/install support.
Send me a message on Discord (username: northfear) and I'll try to figure it out.

**Comment by Northfear** [comment]
We got this sorted out. The crash was happening due to missing [NoTrpDrm](https://github.com/Rinnegatamante/NoTrpDrm) plugin
