### ISSUE TITLE
Error C2-12828-1 when start

### ISSUE THREAD

**Issue by Cering** [Northfear/homm3hd-vita#5]
Thanks for this repository that can play h3 in psvita!

I tried to install it and success, but failed when start game with error `C2-12828-1`, the detail info please see below. 

Can you give some suggestion for how to fix it? Thanks again.

- Error C2-12828-1 screenshot: 
![2023-12-23-183519](https://github.com/Northfear/homm3hd-vita/assets/9027486/a879f314-632a-4aef-a55e-45089b90d680)

- Dump core file: [psp2core-1703327707-0x00001526b9-eboot.bin.psp2dmp.zip](https://github.com/Northfear/homm3hd-vita/files/13758820/psp2core-1703327707-0x00001526b9-eboot.bin.psp2dmp.zip)

- `HOMM3.vpk` version is v1.2.2
- System version of psvita is 3.60 (HENkaku-11)
- All plugin files are put in `ur0:/tai`, and the contents of `ur0:/tai/config.txt` is:
```bash
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/gamesd.skprx
ur0:tai/nonpdrm_v1.2.skprx
ur0:tai/repatch_v3.0.skprx
ur0:tai/0syscall6_v1.3.skprx
ur0:tai/ioplus_v0.1.skprx
ur0:tai/kubridge_v0.1.skprx
*ALL
ur0:tai/VitaGrafix_v5.0.2.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
ur0:tai/shellbat_r10.suprx
ur0:tai/LowMemMode_v1.2.suprx
ur0:tai/NoTrpDrm_v1.1.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx

```

**Comment by Northfear** [comment]
Can you give this version a try?
https://github.com/Northfear/homm3hd-vita/releases/tag/v1.1.0
Also what's your game data version?

**Comment by Cering** [comment]
Reinstall with `HOMM3_v1.1.0.vpk` and it works fine, Thanks!

**Comment by Northfear** [comment]
Whoa! It's not fine =)
Performance of 1.1.0 is pretty bad during big battles. Can you contact me on Discord (username: northfear), so we could investigate this further?
Or at least run a testing version/send me some dump from it?

**Comment by Cering** [comment]
of course, already add you in Discord (Cering)

**Comment by Northfear** [comment]
The problem was caused by missing libshacccg.suprx
After following the [guide](https://cimmerian.gitbook.io/vita-troubleshooting-guide/shader-compiler/extract-libshacccg.suprx) everything worked as expected
